apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apigateway.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.apigateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apigateway.name }}
    spec:
      containers:
        - name: {{ .Values.apigateway.name }}
          image: "{{ .Values.apigateway.image.repository }}:{{ .Values.apigateway.image.tag }}"
          imagePullPolicy: {{ .Values.apigateway.image.pullPolicy }}
          env:
            # Catalog Service Route
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
              value: "catalog-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
              value: "http://catalog-service:8081"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
              value: "Path=/api/v1/products/**,/api/v1/admin/products/**,/api/v1/admin/product-imports/**"

            # Search Service Route
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
              value: "search-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
              value: "http://search-service:8083"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
              value: "Path=/api/v1/search/**"
          ports:
            - name: http
              containerPort: 8080