apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: {{ .Values.apigateway.type }}
  ports:
    - port: {{ .Values.apigateway.port }}
      targetPort: http
      nodePort: 31000
  selector:
    app: api-gateway