apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: {{ index .Values "catalog-service" "type" }}
  ports:
    - port: {{ index .Values "catalog-service" "port" }}
      targetPort: http
  selector:
    app: catalog-service