apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.elastic.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.elastic.storageSize }}
