apiVersion: v1
kind: Service
metadata:
  name: product-import-worker-service
spec:
  type: {{ index .Values "product-import-worker-service" "type" }}
  ports:
    - port: {{ index .Values "product-import-worker-service" "port" }}
      targetPort: http
  selector:
    app: product-import-worker-service