apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ index .Values "product-import-worker-service" "name" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ index .Values "product-import-worker-service" "name" }}
  template:
    metadata:
      labels:
        app: {{ index .Values "product-import-worker-service" "name" }}
    spec:
      containers:
        - name: {{ index .Values "product-import-worker-service" "name" }}
          image: "{{ (index .Values "product-import-worker-service").image.repository }}:{{ (index .Values "product-import-worker-service").image.tag }}"
          imagePullPolicy: {{ .Values.catalog.image.pullPolicy }}
          env:
            # Use the Service Name 'catalog-db' instead of localhost
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://catalog-db:5432/catalogdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: "kafka-0.kafka-svc:9092"
            - name: SPRING_FLYWAY_BASELINE-ON-MIGRATE
              value: "true"
          ports:
            - name: http
              containerPort: 8082