apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  type: {{ index .Values "search-service" "type"  }}
  ports:
    - port: {{ index .Values "search-service" "port" }}
      targetPort: http
  selector:
    app: search-service