version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: shop-postgres
    environment:
#      POSTGRES_DB: catalogdb
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.2-alpine
    container_name: shop-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: shop-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: shop-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: ecommerce-prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: [ "9090:9090" ]
  grafana:
    image: grafana/grafana:11.0.0
    container_name: ecommerce-grafana
    ports: [ "3000:3000" ]
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    depends_on: [ prometheus ]

  catalog-service:
    build:
      context: .
      dockerfile: catalog-service/Dockerfile
    container_name: catalog-service
    ports:
      - "8081:8081"

  product-import-service:
    build:
      context: .
      dockerfile: product-import-worker/Dockerfile
    container_name: product-import-service
    ports:
      - "8082:8082"

  cart-service:
    build:
      context: .
      dockerfile: cart-service/Dockerfile
    container_name: cart-service
    ports:
      - "8086:8086"

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    container_name: inventory-service
    ports:
      - "8085:8085"

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "8087:8087"

  api-service:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-service
    ports:
      - "8080:8080"

volumes:
  postgres_data:
